/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'zhouwc' at '17-9-13 上午1:29' with Gradle 3.2-rc-1
 *
 * @author zhouwc, @date 17-9-13 上午1:29
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
